title: af-jekyl
description: af-jekyl description

lang: en-US

baseURL: "https://appfoundry.be/"

github:
  organization: "AppFoundry"
  project: "Reliant"
  downloads: true

projectStatus:
    podName: "Reliant"
    supportsCarthage: true

logo:
  brand:
    name: "Reliant"
    punchline: "dependency injection for iOS and OSX"
  pngFile: "direkt_logo.png"
  # svgFile:
  #   path: "project_logo.svg" # relative in `_includes` folder
  #   id: "Reliant_Logo"

style:
  themeColor: "#336699"
  accentColor: "#3366FF"
  textColor: "#FFFFFF"

twitter: "AppFoundryBE"
mail: "info@appfoundry.be"
headerImage: "header_image.png" # relative to `assets/images`

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      comments: false

exclude:
  - vendor/bundle
