title: af-jekyl
description: af-jekyl description

lang: en-US

baseURL: "https://appfoundry.be/"

logo:
  brand:
    name: "Reliant"
    punchline: "dependency injection for iOS and OSX"
  svgId: ""
  # OR - 
  # pngFile: "header_image.png"

headerImage: "header_image.png"

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      comments: false

exclude:
  - vendor/bundle
